
CREATE OR ALTER PROCEDURE sp_AdicionarCurso(
    @SIGLA CHAR(3),
    @NOME_CURSO VARCHAR(50)
)
AS
BEGIN
    INSERT CURSOS (CURSO, NOME) VALUES (@SIGLA, @NOME_CURSO)
    SELECT * FROM CURSOS WHERE CURSO = @SIGLA
END
GO

EXEC sp_AdicionarCurso @SIGLA = 'DIR',
                       @NOME_CURSO = 'DIREITO'