
INSERT PROFESSOR (NOME) VALUES ('GLAUCIO')
GO

CREATE OR ALTER PROCEDURE sp_AdicionarProfessor
(
    @NOME_PROFESSOR VARCHAR(50) 
)
AS
BEGIN
    INSERT PROFESSOR (NOME) VALUES (@NOME_PROFESSOR)
    SELECT * FROM PROFESSOR WHERE NOME = @NOME_PROFESSOR
END
GO

EXEC sp_AdicionarProfessor 'BRUNO'
GO

