-- VO CRIAR PRA COLOCAR PRIMEIRAMENTE SOMENTE AS QUE NAO PODEM SER NULL, OQ PODE SERA COLOCADO APÓS!!!!!!!!!!!

CREATE OR ALTER PROCEDURE sp_CadastrarMatricula(
    @MATRICULA INT,
    @CURSO CHAR(3),
    @PERLETIVO INT
)
AS
BEGIN
    --VOU INSERIR AS COISAS DO CABOCLO
    INSERT INTO MATRICULA (MATRICULA, MATERIA, CURSO, PROFESSOR, PERLETIVO) 
    SELECT @MATRICULA, MATERIAS.SIGLA, @CURSO, MATERIAS.PROFESSOR, @PERLETIVO
    FROM MATERIAS WHERE CURSO = @CURSO
END
GO

EXEC sp_CadastrarMatricula @MATRICULA = 2,
                           @CURSO = 'ENG',
                           @PERLETIVO = 2025


    
-- cara achei fodástico essa mandinga